name: flutter_application_1
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.4.5
  firebase_core: ^2.8.0
  firebase_auth: ^4.4.0
  flutter_iconly: ^1.0.2
  card_swiper: ^2.0.4
  fancy_shimmer_image: ^2.0.2
  page_transition: ^2.0.9
  provider: ^6.0.5
  badges: ^3.0.3
  shared_preferences: ^2.1.0
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.1.5
  build_runner: ^2.1.8


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/cat/
    - assets/images/landing/
    - assets/images/offres/
  #   - images/a_dot_ham.jpeg


#  fonts:
#    - family: DMSans
#      fonts:
#        - asset: fonts/DMSans-Bold.ttf
#        - asset: fonts/DMSans-Medium.ttf
#        - asset: fonts/DMSans-Regular.ttf


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

